name: Publish

on:
  workflow_dispatch:

jobs:
  orchestrate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Create new release
        run: |
          cargo install cargo-extract
          VERSION=v$(cargo extract package.version)
          echo "Creating release: ${VERSION}"
          gh release create ${VERSION} --title ${VERSION}
          cargo publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
